backend:
  name: github
  repo: minetaro12/minetaro12pages
media_folder: /static/images
public_folder: /images
publish_mode: editorial_workflow
show_preview_links: false
collections:
  - name: 'post'
    label: 'post'
    folder: 'content/post'
    create: true
    slug: 'index'
    path: '{{year}}/{{month}}/{{folder}}/{{slug}}'
    identifier_field: title
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', format: 'YYYY-MM-DD HH:mm:ss' }
      - { label: 'Summary', name: 'summary', widget: 'string' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Folder', name: 'folder', widget: 'string' }
